### GET /telefone/all

GET http://localhost:5074/telefone/all
Accept: application/json

###

### GET /telefone/{id}

GET http://localhost:5074/telefone/13
Accept: application/json

###

### POST /telefone?id_pessoa=1

POST http://localhost:5074/telefone?id_pessoa=1
Content-Type: application/json
Accept: application/json

{
  "tipo": "Celular",
  "numero": "31232"
}

###

### PUT /telefone

PUT https://localhost:7101/telefone?Id_telefone=3
Content-Type: application/json
Accept: application/json

 {
    "id_telefone": 3,
    "tipo": "Celular",
    "numero": "3123211312",
    "PessoaId": "1"
  }

###

### DELETE /telefone?id=6

DELETE http://localhost:5074/telefone?id=25
Accept: application/json

###