### GET /pessoa/all

GET http://localhost:5074/pessoa/all
Accept: application/json

###

### GET /pessoa/{id}

GET http://localhost:5074/pessoa/{id}
Accept: application/json

###

### GET /pessoa/GetByNome?nome=Fabiano

GET http://localhost:5074/pessoa/GetByNome?nome=Fabiano
Accept: application/json

###

### GET /pessoa/GetPessoaByTelefone?numero=123456789

GET http://localhost:5074/pessoa/GetPessoaByTelefone?numero=123456789
Accept: application/json

###

### POST /pessoa

POST http://localhost:5074/pessoa
Content-Type: application/json
Accept: application/json

{
  "nome": "Fabiano",
  "data_nascimento": "1990-01-01",
  "ativo": true,
  "cpf": "07738062967",
  "genero": "M",
  "endereco": "Rua ABC",
  "email": "joao@example.com"
}

###

### PUT /pessoa

PUT http://localhost:5074/pessoa
Content-Type: application/json
Accept: application/json

{
  "id_pessoa": 14,
  "nome": "Fabiano",
  "data_nascimento": "1990-01-01",
  "ativo": true,
  "cpf": "07738062967",
  "genero": "M",
  "endereco": "Rua ABC",
  "email": "joao@example.com",
  "data_cadastro": "2024-03-17T16:09:16.882476"
}

###

### DELETE /pessoa/{id}

DELETE http://localhost:5074/pessoa/12
Accept: application/json

###

### GET /telefone/all

GET http://localhost:5074/telefone/all
Accept: application/json

###

### GET /telefone/{id}

GET http://localhost:5074/telefone/13
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImZhYmlhbm8iLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTA3ODQ3OTUsImV4cCI6MTcxMDc4ODM5NSwiaWF0IjoxNzEwNzg0Nzk1fQ.gHXYlq9Z_Vk5JgACtwnJMWxtsAu87A_4HiMTig3CIIs


###

### POST /telefone?id_pessoa=1

POST http://localhost:5074/telefone?id_pessoa=1
Content-Type: application/json
Accept: application/json

{
  "tipo": "Celular",
  "numero": "123456789"
}

###

### PUT /telefone

PUT http://localhost:5074/telefone
Content-Type: application/json
Accept: application/json

{
  "id_telefone": 6,
  "tipo": "Celular",
  "numero": "123456789"
}

###

### DELETE /telefone?id=6

DELETE http://localhost:5074/telefone?id=6
Accept: application/json

###

### GET /usuario/all

GET http://localhost:5074/usuario/all
Accept: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImZhYmlhbm8iLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTA3ODQ3OTUsImV4cCI6MTcxMDc4ODM5NSwiaWF0IjoxNzEwNzg0Nzk1fQ.gHXYlq9Z_Vk5JgACtwnJMWxtsAu87A_4HiMTig3CIIs
###

### POST /usuario/register

POST http://localhost:5074/usuario/register
Content-Type: application/json
Accept: application/json

{
  "username": "fabiano1",
  "password": "fabiano",
  "role": "employee"
}

###

### POST /usuario/login

POST http://localhost:5074/usuario/login
Content-Type: application/json
Accept: application/json

{
  "username": "fabiano1",
  "password": "fabiano"
}

###

### DELETE /usuario

DELETE https://localhost:7101/usuario
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImZhYmlhbm8iLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTA3ODQzMzksImV4cCI6MTcxMDc4NzkzOSwiaWF0IjoxNzEwNzg0MzM5fQ.89yBR6wAI0228Ze8BFyKOXfm44T6W0Dg2voFpOH_kkU

{
  "username": "fabiano",
  "password": "fabiano"
}
